apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
- path: patches/hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: gitopsdemo
- path: patches/image-policy.yaml
  target:
    kind: ImagePolicy
    name: gitopsdemo