name: Flux Auto-PR
on:
  push:
    branches:
      - flux-image-updates

permissions:
  pull-requests: write

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout
    - name: pull-request
      run: |
        gh pr create --title "Pull request title" --body "Pull request body"