name: .NET Docker CI

on:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE_NAME: gitopsdemo

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        GIT_HASH=$(git rev-parse --short HEAD)
        docker build -f src/GitopsDemoApi/Dockerfile -t ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${GIT_HASH} .

    - name: Push Docker image
      run: |
        GIT_HASH=$(git rev-parse --short HEAD)
        GIT_DATE=$(date +%s)
        docker push ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${GIT_HASH}
        docker tag ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${GIT_HASH} ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${{ github.ref_name }}-${GIT_HASH}-${GIT_DATE}
        docker push ghcr.io/${{ github.actor }}/${DOCKER_IMAGE_NAME}:${{ github.ref_name }}-${GIT_HASH}-${GIT_DATE}