name: Release Docker Image

on:
  push:
    tags:
      - 'v*'
env:
  DOCKER_IMAGE_NAME: gitopsdemo
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --generate-notes